name: Auto-merge labeled PRs

on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Auto-merge PRs with 'auto-merge' label
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: "${{ secrets.PAT }}"
          MERGE_LABELS: "auto-merge" # Only PRs with this label will be considered
          MERGE_METHOD: "squash"
          MERGE_REQUIRED_APPROVALS: 0
